### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lebik** [vavkamil/XSSwagger#1]
Hi, thanks for the scanner first of all!

I ran the XSSwagger, but got an error:
```

[i] Scanning a single domain: swagger.domain.net 


****************************************************************************************************
****************************************************************************************************

[ 200 ] [ Swagger UI ] https://swagger.domain.net//swagger/index.html
Traceback (most recent call last):
  File "xsswagger.py", line 275, in <module>
    check_domain(domain)
  File "xsswagger.py", line 257, in check_domain
    version_detected = check_version(url, response)
  File "xsswagger.py", line 217, in check_version
    version_detected = pr2[2]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by imparabl3** [comment]
Hi, Is there any way to resolve this issue?

**Comment by rokkamvamshi** [comment]
Hi buddy ! I too got the same problem.
I have done some changes to it, now its working perfectly.
You can replace the check_version function with this:

```
def check_version(url, html):
    if re.search("(?<='|\")(.*?)swagger-ui.js(?='|\")", html):
        pr1 = re.search("(?<='|\")(.*?)swagger-ui.js(?='|\")", html)
        swagger_js_path = pr1.group()
        # swagger_js_path = re.sub('^.', '', swagger_js_path)
        url = re.sub("index.html", "", url)
        # print(swagger_js_path)
        swagger_ui_js = urllib.parse.urljoin(url + "/", swagger_js_path)
        # print(swagger_ui_js)
        response = requests.get(url=swagger_ui_js)
        pr1 = re.findall(
            "@version\sv(.*?)$", response.content.decode("utf-8"), re.MULTILINE
        )
        version_detected = pr1[0]
    elif re.search("(?<='|\")(.*?)swagger-ui-bundle.js(?='|\")", html):
        pr2 = re.search("(?<='|\")(.*?)swagger-ui-bundle.js(?='|\")", html)
        swagger_bundle_path = pr2.group(0)
        # swagger_bundle_path = re.sub('^.', '', swagger_bundle_path)
        # print("1", swagger_bundle_path)
        swagger_bundle_js = urllib.parse.urljoin(url + "/", swagger_bundle_path)
        # print("2", swagger_bundle_js)
        response2 = requests.get(url=swagger_bundle_js)
        pr2 = re.search(
            'd=!0,h="(.*?)",v="(.*?)",m="(.*?)",(g|y)="(.*?)";',
            response2.content.decode("utf-8"),
        )
        if pr2:
            version_detected = pr2[2]
        else:
            version_detected = "error"
    else:
        version_detected = "error"

    return version_detected
```

Now you should be able to use the tool successfully
